apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: vegan-backend-cm
data:
  dsn: "root:123456@tcp(mysql-fox.{{ .Release.Namespace }}.svc:3306)/vegan?charset=utf8mb4&parseTime=True&loc=Local"