apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vegan-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:

  tls:
    - hosts:
      - vegan.test
      secretName: tls-secret
  rules:
  - host: vegan.test
    http:
      paths:
      - path: /api/
        pathType: Prefix
        backend:
          service:
           name: vegan-backend-svc
           port: 
            number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
           name: vegan-frontend-svc
           port: 
            number: 80
