{{ if eq .Values.vegan.networkPolicy "blacklist" }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: network-vegan
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      prj: vegan
  policyTypes:
    - Ingress

  ingress:
    - from:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.244.0.0/24
        - podSelector:
            matchLabels:
              prj: vegan
{{ end }}             
