apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: viewer
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods","services","ingress","configmaps"]
  verbs: ["get", "watch", "list"]