apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.vegan.fullName }}-backend-svc
spec:
  selector:
     {{ toYaml .Values.vegan.backend.labels }}
  type: NodePort
  ports:
    - port: {{ .Values.vegan.backend.port }}
      targetPort: {{ .Values.vegan.backend.serverPort }}
      nodePort: {{ .Values.vegan.backend.nodePort }}